network:
  default_connection: localhost_tcp
  connections:
    a_tls_connection:
      type: tls
      ip: 192.168.1.1
      port: 15555
      cert_path: /path/to/cert.pem
      key_path: /path/to/key.pem
    localhost_tcp:
      type: tcp
      ip: 127.0.0.1
      port: 12345

aligner:
  type: "adam"
  learning_rate: 0.01

peer_discovery:
  temp_live_data_shim_address: "10.1.20.59:12345"

daemon:
  server_type: "unix_socket"
  server_address: "~/.nestbox/socket/daemon.sock"

database:
  type: "redis"
  host: "localhost"
  port: 6379
